package course.qa.selenium;// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;

public class CreateNewArticleIDETest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @BeforeEach
    public void setUp() {
        // Driver management and WebDriver instantiation
        ChromeOptions options = new ChromeOptions();
        options.setAcceptInsecureCerts(true);
        driver = WebDriverManager.getInstance(ChromeDriver.class).capabilities(options).create();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @AfterEach
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void listallarticles() {
        driver.get("https://localhost:8081/articles");
        driver.manage().timeouts().implicitlyWait(Duration.ofMillis(3000));
        driver.manage().window().setSize(new Dimension(1722, 936));
        driver.findElement(By.linkText("Add Article")).click();
        driver.findElement(By.id("title")).click();
        driver.findElement(By.id("title")).sendKeys("New Article");
        driver.findElement(By.id("content")).click();
        driver.findElement(By.id("content")).sendKeys("Spring is grate ...");
        // 9 | type | id=file | C:\Users\office27\Pictures\java2days.png
        driver.findElement(By.id("file")).sendKeys("C:\\Users\\office27\\Pictures\\java2days.png");
        // 10 | click | id=submit |
        driver.findElement(By.id("submit")).click();
        // 11 | click | xpath=//tr[last()]/td[6]/a/img |
        driver.findElement(By.xpath("//tr[last()]/td[6]/a/img")).click();
        // 12 | mouseOver | css=tr:last-child .img-thumbnail |
        {
            WebElement element = driver.findElement(By.cssSelector("tr:last-child .img-thumbnail"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        // 13 | mouseOut | css=tr:last-child .img-thumbnail |
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        // 14 | click | css=.btn-secondary |
        driver.findElement(By.cssSelector(".btn-secondary")).click();
    }
}
