package selenium;// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.*;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;

public class ListallarticlesTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void listallarticles() {
    driver.get("https://localhost:8081/articles");
    driver.manage().window().setSize(new Dimension(1338, 880));
    driver.findElement(By.linkText("Add Article")).click();
    driver.findElement(By.id("content")).click();
    driver.findElement(By.id("content")).sendKeys("Spring is grate ...");
    driver.findElement(By.id("title")).click();
    driver.findElement(By.id("title")).sendKeys("New Article");
    driver.findElement(By.id("file")).click();
    driver.findElement(By.id("file")).sendKeys("C:\\fakepath\\java2days.png");
    driver.findElement(By.id("submit")).click();
    driver.findElement(By.cssSelector("tr:nth-child(9) .btn-danger")).click();
    driver.findElement(By.cssSelector("tr:nth-child(5) .btn-danger")).click();
    driver.findElement(By.id("navbarDropdown")).click();
    driver.findElement(By.linkText("Articles")).click();
    driver.findElement(By.linkText("Add Article")).click();
    driver.findElement(By.id("cancel")).click();
  }
}
