package selenium;// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;
public class ListallarticlesTest2 {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void listallarticles() {
    // Test name: List all articles
    // Step # | name | target | value
    // 1 | open | https://localhost:8081/articles | 
    driver.get("https://localhost:8081/articles");
    // 2 | setWindowSize | 1338x880 | 
    driver.manage().window().setSize(new Dimension(1338, 880));
    // 3 | click | linkText=Add Article | 
    driver.findElement(By.linkText("Add Article")).click();
    // 4 | click | id=content | 
    driver.findElement(By.id("content")).click();
    // 5 | type | id=content | Spring is grate ...
    driver.findElement(By.id("content")).sendKeys("Spring is grate ...");
    // 6 | click | id=title | 
    driver.findElement(By.id("title")).click();
    // 7 | type | id=title | New Article
    driver.findElement(By.id("title")).sendKeys("New Article");
    // 8 | click | id=file | 
    driver.findElement(By.id("file")).click();
    // 9 | type | id=file | C:\fakepath\java2days.png
    driver.findElement(By.id("file")).sendKeys("C:\\fakepath\\java2days.png");
    // 10 | click | id=submit | 
    driver.findElement(By.id("submit")).click();
    // 11 | click | css=tr:nth-child(9) .btn-danger | 
    driver.findElement(By.cssSelector("tr:nth-child(9) .btn-danger")).click();
    // 12 | click | css=tr:nth-child(5) .btn-danger | 
    driver.findElement(By.cssSelector("tr:nth-child(5) .btn-danger")).click();
    // 13 | click | id=navbarDropdown | 
    driver.findElement(By.id("navbarDropdown")).click();
    // 14 | click | linkText=Articles | 
    driver.findElement(By.linkText("Articles")).click();
    // 15 | click | linkText=Add Article | 
    driver.findElement(By.linkText("Add Article")).click();
    // 16 | click | id=cancel | 
    driver.findElement(By.id("cancel")).click();
  }
}
